apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flow-inventory-service-appdata
  labels:
    app.kubernetes.io/part-of: flow-inventory-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
