apiVersion: v1
kind: Service
metadata:
  name: flow-inventory-service-db
  labels:
    app.kubernetes.io/part-of: flow-inventory-service
spec:
  type: ClusterIP
  selector:
    app: flow-inventory-service-db
  ports:
  - name: db
    port: 5432
    targetPort: db
