import os
from pathlib import Path
from typing import Dict, Any
from app.orchestrator.state import GenerationAgentState
from app.models.session import SessionPhase

def _to_pascal_case(text: str) -> str:
    cleaned = text.replace("-", " ").replace("_", " ")
    return "".join(word.capitalize() for word in cleaned.split())

def scaffolder_node(state: GenerationAgentState) -> Dict[str, Any]:
    blueprint = state.get("blueprint", {})
    service_name = blueprint.get("serviceName") or blueprint.get("service_name", "sample-service")
    package_name = blueprint.get("packageName") or blueprint.get("package_name", "com.corp.service")
    workspace_path = state.get("workspace_path", "./workspaces/sample")
    generated_files = state.get("generated_files", {})
    logs = state.get("logs", [])

    logs.append(f"[SCAFFOLDER] Generating project scaffolding for {service_name}")
    pascal_name = _to_pascal_case(service_name)
    pkg_path = package_name.replace(".", "/")

    # 1. pom.xml with Java 21, Spring Boot 3.2.3, Mockito
    pom_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.3</version>
        <relativePath/>
    </parent>
    <groupId>{package_name}</groupId>
    <artifactId>{service_name}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>{service_name}</name>
    <description>Autonomous Microservice generated by Microservice Code Studio</description>
    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>
            </plugin>
        </plugins>
    </build>
</project>
"""

    # 2. application.yml
    app_yml = f"""spring:
  application:
    name: {service_name}
  datasource:
    url: jdbc:h2:mem:{service_name.replace('-', '_')};DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
"""

    # 3. Application.java
    app_java = f"""package {package_name};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class {pascal_name}Application {{
    public static void main(String[] args) {{
        SpringApplication.run({pascal_name}Application.class, args);
    }}
}}
"""

    generated_files["pom.xml"] = pom_xml
    generated_files["src/main/resources/application.yml"] = app_yml
    generated_files[f"src/main/java/{pkg_path}/{pascal_name}Application.java"] = app_java

    # Write files to disk
    base_dir = Path(workspace_path)
    for rel_path, content in generated_files.items():
        file_path = base_dir / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")

    logs.append(f"[SCAFFOLDER] Created pom.xml, application.yml, and {pascal_name}Application.java")

    return {
        "current_phase": SessionPhase.CODE_GENERATION.value,
        "generated_files": generated_files,
        "logs": logs
    }
