import logging
import re
from pathlib import Path
import uuid
from typing import Dict, List, Tuple
from app.services.injection_guard import assert_no_injection
from app.services.specification_guard import assert_looks_like_specification
from app.config import settings
from app.models.blueprint import (
    ArchitectureBlueprint,
    DomainEntity,
    EntityAttribute,
    UserStoryRecord,
    AcceptanceScenarioRecord,
    SpecificationSummary,
)

#: Cache in front of the on-disk store. Ingested blueprints used to live ONLY here, so a
#: restart lost them and the ingest-then-generate flow broke at its second step.
SPECIFICATIONS_STORE: Dict[str, ArchitectureBlueprint] = {}

logger = logging.getLogger(__name__)


def _specification_path(spec_id: str) -> Path:
    """Where one blueprint is persisted. The id is generated by `save_specification`."""
    return Path(settings.SPECIFICATION_DIR) / f"{spec_id}.json"


def _parse_emitted_entities(content: str) -> List[DomainEntity]:
    """Read the entity layout this application writes.

    ``### Customer (`customers`)`` followed by ``- `id`: Long — PK, required`` bullets.

    Types and flags are taken verbatim rather than mapped through a table: the document
    already states them, and a mapping layer is where a type silently changes.
    """
    entities: List[DomainEntity] = []

    for match in re.finditer(
        r"(?m)^###\s+([A-Za-z][A-Za-z0-9_]*)\s*\(`([^`]+)`\)\s*$"
        r"(.*?)(?=^###\s|^##\s|\Z)",
        content,
        re.DOTALL,
    ):
        name, table_name, body = match.group(1), match.group(2), match.group(3)
        attributes: List[EntityAttribute] = []

        for attr_match in re.finditer(
            r"(?m)^-\s*`([A-Za-z_][A-Za-z0-9_]*)`:\s*([A-Za-z][A-Za-z0-9_<>\[\], ]*?)"
            r"\s*(?:—|-|--)\s*([^\n]*)$",
            body,
        ):
            attr_name, attr_type, flags = (
                attr_match.group(1),
                attr_match.group(2).strip(),
                attr_match.group(3).lower(),
            )
            attributes.append(
                EntityAttribute(
                    name=attr_name,
                    type=attr_type,
                    isPrimaryKey="pk" in flags,
                    nullable="required" not in flags,
                    validationRules=["@NotNull"] if "required" in flags else [],
                )
            )

        if attributes:
            entities.append(
                DomainEntity(name=name, tableName=table_name, attributes=attributes)
            )

    return entities



def _parse_bulleted_stories(content: str) -> List[UserStoryRecord]:
    """Read the bulleted story layout.

        - **US-1**: As a Buyer, I want to create an order, so that I can buy items.
          - **AC-1.1**: Given valid items, when POST /orders is called, then it is created.

    A third layout, alongside ``### User Story N - Title (Priority: P1)`` and the app's own
    entity headings. It was previously not read at all: the parser found no stories and the
    fabricated "US-1 / manage resources" placeholder was substituted, which is why an e2e
    test asserting that ingestion works passed while parsing nothing.
    """
    stories: List[UserStoryRecord] = []

    for match in re.finditer(
        r"(?m)^\s*-\s*\*\*(US-?\d+)\*\*\s*:\s*(.+?)"
        r"(?=^\s*-\s*\*\*US-?\d+\*\*|\Z)",
        content,
        re.DOTALL,
    ):
        story_id = match.group(1).replace("US-", "US-").replace("US--", "US-")
        body = match.group(2)

        prose = body.split("\n", 1)[0].strip()
        role = "User"
        intent = prose
        benefit = ""
        role_match = re.search(r"\bAs an?\s+([^,]+),", prose, re.IGNORECASE)
        if role_match:
            role = role_match.group(1).strip()
        want_match = re.search(r"\bI want\s+(.+?)(?:,\s*so that|$)", prose, re.IGNORECASE)
        if want_match:
            intent = re.sub(r"^to\s+", "", want_match.group(1).strip())
        benefit_match = re.search(r"\bso that\s+(.+)$", prose, re.IGNORECASE)
        if benefit_match:
            benefit = benefit_match.group(1).strip().rstrip(".")

        scenarios: List[AcceptanceScenarioRecord] = []
        for ac_match in re.finditer(
            r"\*\*(AC-[\w.\-]+)\*\*\s*:\s*(.+?)(?=$|\n\s*-\s*\*\*(?:AC|US))",
            body,
            re.DOTALL,
        ):
            ac_id, ac_text = ac_match.group(1), " ".join(ac_match.group(2).split())
            given = when = then = ""
            gwt = re.search(
                r"given\s+(.+?)\s*,?\s*when\s+(.+?)\s*,?\s*then\s+(.+?)\.?$",
                ac_text,
                re.IGNORECASE,
            )
            if gwt:
                given, when, then = (g.strip().rstrip(".,") for g in gwt.groups())
            else:
                # No Given/When/Then phrasing: keep the sentence as the expected outcome
                # rather than splitting it into invented clauses.
                then = ac_text.rstrip(".")
            scenarios.append(
                AcceptanceScenarioRecord(
                    scenarioId=ac_id, given=given, when=when, then=then
                )
            )

        if not scenarios:
            # The record requires at least two clauses of some length; refusing here is
            # honest, and the caller is told the document could not be read.
            continue

        stories.append(
            UserStoryRecord(
                id=story_id,
                priority="P1",
                role=role,
                intent=intent or prose,
                benefit=benefit,
                scenarios=scenarios,
            )
        )

    return stories


def parse_spec_markdown(content: str) -> ArchitectureBlueprint:
    # Asked "que dia es hoy?" this used to return a VALID blueprint: entity `Resource`
    # with `id`/`name`, story `US-1` "manage resources", and the scenario "service is
    # running / endpoint is called / returns successful response". Nothing in the document
    # said any of that. Measured: uploading that text returned 201 with `entityCount: 1,
    # storyCount: 1, isValid: true, validationWarnings: []`, so every document produced a
    # "valid" specification and the caller had no way to learn their file was unreadable.
    assert_looks_like_specification(content, field="document")

    """
    Parses standard Spec Kit Markdown files extracting service name,
    entities, user stories, and Given/When/Then scenarios.
    """
    # 1. Extract Service Name
    branch_match = re.search(r"\*\*Feature Branch\*\*:\s*`([^`]+)`", content)
    if branch_match:
        raw_name = branch_match.group(1)
        # Strip sequential numbering like 001- if present
        clean_name = re.sub(r"^\d+-", "", raw_name)
    else:
        title_match = re.search(r"# Feature Specification:\s*(.+)", content)
        if title_match:
            clean_name = title_match.group(1).strip().lower().replace(" ", "-")
        else:
            clean_name = "app-service"

    package_name = f"com.corp.{clean_name.replace('-', '.')}"

    # 2. Extract Entities
    #
    # TWO formats, because the app both consumes and produces these documents and they
    # disagreed. This parser only understood the Spec Kit layout:
    #
    #     ### Key Entities
    #     - **Customer**: id (Long), email (String)
    #
    # while `lifecycle_artifacts` writes the layout every generated session contains:
    #
    #     ## Domain Entities
    #     ### Customer (`customers`)
    #     - `id`: Long — PK, required
    #
    # So uploading a spec.md the app itself produced found NO entities and fell through to
    # the fabricated `Resource` below -- which is why the round-trip appeared to work and
    # why an unreadable document returned `isValid: true`. Round-tripping its own output is
    # the least a generator can do.
    entities: List[DomainEntity] = []
    entities = _parse_emitted_entities(content)
    entity_section = re.search(r"### Key Entities.*?(?=##|\Z)", content, re.DOTALL)
    if not entities and entity_section:
        entity_matches = re.findall(r"-\s*\*\*([A-Za-z0-9]+)\*\*:\s*(.+)", entity_section.group(0))
        for name, desc in entity_matches:
            attrs = [EntityAttribute(name="id", type="UUID", isPrimaryKey=True)]
            # Look for extra attributes in description
            attr_matches = re.findall(r"(\w+)\s*\(([^)]+)\)", desc)
            for attr_name, attr_type_str in attr_matches:
                if attr_name.lower() != "id":
                    attrs.append(EntityAttribute(
                        name=attr_name,
                        type="String" if "String" in attr_type_str else "BigDecimal" if "BigDecimal" in attr_type_str else "Long",
                        nullable=False,
                        validationRules=["@NotNull"] if "@NotNull" in attr_type_str else ["@NotBlank"] if "@NotBlank" in attr_type_str else []
                    ))
            entities.append(DomainEntity(
                name=name,
                tableName=name.lower() + "s",
                attributes=attrs
            ))

    if not entities:
        # Was a fabricated `Resource` entity with `id`/`name`. Inventing a domain made an
        # unreadable document look like a parsed one, and the invention is what a service
        # would then be generated from. Say what could not be found instead.
        raise ValueError(
            "No domain entities could be read from this document. A specification needs "
            "entity definitions -- for example a '### Entity: Customer' heading with its "
            "attributes -- before a service can be generated from it."
        )

    # 3. Extract User Stories and Given/When/Then scenarios
    user_stories: List[UserStoryRecord] = []
    story_blocks = re.findall(r"### User Story (\d+)\s*-\s*([^\n(]+)(?:\(Priority:\s*(P\d+)\))?(.*?)(?=### User Story|\Z)", content, re.DOTALL)
    
    for story_idx, story_title, priority, story_body in story_blocks:
        story_id = f"US-{story_idx}"
        prio = priority.strip() if priority else "P1"
        
        # Extract scenarios: Given X, When Y, Then Z
        scenarios: List[AcceptanceScenarioRecord] = []
        scenario_matches = re.findall(
            r"(?:(\d+)\.\s*)?\*\*Given\*\*\s*(.*?),\s*\*\*When\*\*\s*(.*?),\s*\*\*Then\*\*\s*([^\n.]+)",
            story_body,
            re.IGNORECASE
        )
        
        for sc_idx, given, when, then in scenario_matches:
            sc_id = f"AC-{story_idx}.{sc_idx or len(scenarios) + 1}"
            scenarios.append(AcceptanceScenarioRecord(
                scenarioId=sc_id,
                given=given.strip(),
                when=when.strip(),
                then=then.strip()
            ))

        if not scenarios:
            # Look for bullet points with Given When Then
            alt_matches = re.findall(r"Given\s+(.*?)\s+When\s+(.*?)\s+Then\s+([^\n.]+)", story_body, re.IGNORECASE)
            for given, when, then in alt_matches:
                scenarios.append(AcceptanceScenarioRecord(
                    scenarioId=f"AC-{story_idx}.{len(scenarios) + 1}",
                    given=given.strip(),
                    when=when.strip(),
                    then=then.strip()
                ))

        if not scenarios:
            # Provide baseline scenario if text had intent
            scenarios.append(AcceptanceScenarioRecord(
                scenarioId=f"AC-{story_idx}.1",
                given="valid request payload",
                when="operation is triggered",
                then="operation succeeds with 200 OK"
            ))

        user_stories.append(UserStoryRecord(
            id=story_id,
            priority=prio,
            role="User",
            intent=story_title.strip(),
            benefit="achieve expected business outcome",
            scenarios=scenarios
        ))

    if not user_stories:
        user_stories = _parse_bulleted_stories(content)

    if not user_stories:
        # Was a fabricated "US-1 / manage resources" story with a generic scenario. Same
        # reasoning as the entity above: a placeholder story satisfies every downstream
        # check while describing nothing.
        raise ValueError(
            "No user stories could be read from this document. A specification needs "
            "story sections -- for example '### User Story 1 - <title>' with Given/When/"
            "Then scenarios -- before a service can be generated from it."
        )

    blueprint = ArchitectureBlueprint(
        serviceName=clean_name,
        packageName=package_name,
        entities=entities,
        userStories=user_stories
    )

    validate_blueprint(blueprint)
    return blueprint

def validate_blueprint(blueprint: ArchitectureBlueprint) -> List[str]:
    """Validates structural and constitutional integrity of blueprint."""
    warnings = []
    
    if not blueprint.entities:
        raise ValueError("Specification must define at least one domain entity")

    for entity in blueprint.entities:
        has_pk = any(attr.isPrimaryKey for attr in entity.attributes)
        if not has_pk:
            raise ValueError(f"Entity '{entity.name}' must have at least one primary key attribute")

    if not blueprint.userStories:
        raise ValueError("Specification must include at least one user story")

    for story in blueprint.userStories:
        if not story.scenarios:
            raise ValueError(f"User Story '{story.id}' must include at least one acceptance scenario (Given/When/Then)")

    return warnings

def save_specification(blueprint: ArchitectureBlueprint) -> SpecificationSummary:
    # Blueprint ingestion is an untrusted-input path: the document comes from the user and
    # is carried into generation. Guarded here rather than in the routes because BOTH
    # endpoints -- JSON submission and markdown upload -- converge on this function, so a
    # route-level check would have covered one of them.
    assert_no_injection(blueprint.model_dump(), field="blueprint")

    spec_id = str(uuid.uuid4())
    warnings = validate_blueprint(blueprint)
    SPECIFICATIONS_STORE[spec_id] = blueprint

    # Persisted, so the id in the returned summary refers to something that still exists
    # after a restart. An unwritable directory must not lose the specification for this
    # process, so the cache above is populated first and failure here is reported, not
    # swallowed silently into a store that pretends to have it.
    try:
        directory = Path(settings.SPECIFICATION_DIR)
        directory.mkdir(parents=True, exist_ok=True)
        _specification_path(spec_id).write_text(
            blueprint.model_dump_json(indent=2), encoding="utf-8"
        )
    except OSError as exc:
        logger.warning(
            "Specification %s could not be persisted (%s); it will not survive a restart",
            spec_id, exc,
        )

    return SpecificationSummary(
        specId=spec_id,
        serviceName=blueprint.serviceName,
        packageName=blueprint.packageName,
        entityCount=len(blueprint.entities),
        storyCount=len(blueprint.userStories),
        isValid=True,
        validationWarnings=warnings
    )

def get_specification(spec_id: str) -> ArchitectureBlueprint:
    """The blueprint for `spec_id`, from the cache or from disk.

    Reading from disk is what makes an ingested specification survive a restart. Without
    it, the description returned by the upload referred to something that no longer existed
    the next time anything touched the process -- reported as `GET` returning "Specification
    not found" for a `specId` the same server had just issued minutes earlier.
    """
    cached = SPECIFICATIONS_STORE.get(spec_id)
    if cached is not None:
        return cached

    path = _specification_path(spec_id)
    if not path.exists():
        raise KeyError(f"Specification {spec_id} not found")

    try:
        blueprint = ArchitectureBlueprint.model_validate_json(path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        raise KeyError(f"Specification {spec_id} could not be read: {exc}") from exc

    SPECIFICATIONS_STORE[spec_id] = blueprint
    return blueprint

