"""Multi-module layout ("capa X en proyecto Y") for the deterministic scaffolder.

A multi-module Maven reactor where each generation stage owns one module, and the
package names inside each module are unchanged so cross-module imports keep
resolving. The reactor is:

    model       <- entities + DTOs            (DOMAIN stage)
    service     <- repository + service + impl (SERVICE stage)
    controller  <- controllers + handler       (CONTROLLER stage)
    bootstrap   <- Application class, config, tests (SCAFFOLDER + TEST stages)

Dependency order: model -> service -> controller -> bootstrap. The Application
class lives in bootstrap (which depends on every other module) so Spring's
component scan finds all layers.

This is data, not prose: the profile decides the layout, and the layout decides
where each stage writes and what each module's pom declares.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

#: Stage -> module directory (no trailing slash).
STAGE_MODULE: Dict[str, str] = {
    "SCAFFOLDER": "bootstrap",
    "DOMAIN": "model",
    "SERVICE": "service",
    "CONTROLLER": "controller",
    "TEST": "bootstrap",
}

#: Reactor module order (dependencies first), and each module's intra-reactor deps.
MODULE_ORDER: List[str] = ["model", "service", "controller", "bootstrap"]
MODULE_DEPS: Dict[str, List[str]] = {
    "model": [],
    "service": ["model"],
    "controller": ["service", "model"],
    "bootstrap": ["controller", "service", "model"],
}

#: Maven dependencies each module declares (in addition to its reactor deps).
MODULE_MAVEN_DEPS: Dict[str, List[str]] = {
    "model": ["spring-boot-starter-data-jpa", "spring-boot-starter-validation"],
    "service": ["spring-boot-starter-data-jpa"],
    "controller": ["spring-boot-starter-web", "spring-boot-starter-validation"],
    "bootstrap": ["spring-boot-starter-web", "spring-boot-starter-test", "h2"],
}


def is_multi_module(plan: Optional[Dict[str, Any]]) -> bool:
    """True when the plan asks for a multi-module reactor (any non-layered profile)."""
    return bool(plan) and plan.get("profile") != "layered"


def module_prefix_for(stage: str, plan: Optional[Dict[str, Any]]) -> str:
    """Directory prefix (e.g. ``"model/"``) for a stage's artifacts, or ``""`` when single-module."""
    if not is_multi_module(plan):
        return ""
    return STAGE_MODULE[stage] + "/"


def _dependency_block(group_id: str, artifact_id: str, version: str = "") -> str:
    v = f"<version>{version}</version>" if version else ""
    return (
        "        <dependency>\n"
        f"            <groupId>{group_id}</groupId>\n"
        f"            <artifactId>{artifact_id}</artifactId>\n"
        f"{v}"
        "        </dependency>"
    )


def _boot_dependency_block(artifact_id: str, scope: str = "") -> str:
    sc = f"\n            <scope>{scope}</scope>" if scope else ""
    return (
        "        <dependency>\n"
        "            <groupId>org.springframework.boot</groupId>\n"
        f"            <artifactId>{artifact_id}</artifactId>{sc}\n"
        "        </dependency>"
    )


def render_reactor_poms(
    service_name: str, package_name: str, plan: Dict[str, Any]
) -> Dict[str, str]:
    """Emit the parent pom plus one child pom per module.

    Returns a map of workspace-relative path -> content. The parent lives at
    ``pom.xml`` (packaging=pom); each child lives at ``<module>/pom.xml``.
    """
    version = "0.0.1-SNAPSHOT"

    modules_xml = "\n".join(f"        <module>{m}</module>" for m in MODULE_ORDER)
    parent_pom = f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.3</version>
        <relativePath/>
    </parent>
    <groupId>{package_name}</groupId>
    <artifactId>{service_name}</artifactId>
    <version>{version}</version>
    <packaging>pom</packaging>
    <name>{service_name}</name>
    <description>Autonomous multi-module microservice generated by Microservice Code Studio</description>
    <properties>
        <java.version>21</java.version>
    </properties>
    <modules>
{modules_xml}
    </modules>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
"""

    poms = {"pom.xml": parent_pom}

    for module in MODULE_ORDER:
        deps = []
        for dep_module in MODULE_DEPS[module]:
            deps.append(_dependency_block(package_name, f"{service_name}-{dep_module}", version))
        for boot_artifact in MODULE_MAVEN_DEPS[module]:
            scope = "test" if boot_artifact == "spring-boot-starter-test" else ""
            if boot_artifact == "h2":
                scope = "runtime"
            deps.append(_boot_dependency_block(boot_artifact, scope))
        deps_xml = "\n".join(deps)

        # bootstrap is the runnable module: it carries the Spring Boot plugin.
        boot_plugin = ""
        if module == "bootstrap":
            boot_plugin = """        <build>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </build>
"""

        child = f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>{package_name}</groupId>
        <artifactId>{service_name}</artifactId>
        <version>{version}</version>
    </parent>
    <artifactId>{service_name}-{module}</artifactId>
    <name>{service_name}-{module}</name>
    <dependencies>
{deps_xml}
    </dependencies>
{boot_plugin}</project>
"""
        poms[f"{module}/pom.xml"] = child

    return poms
