"""Deterministic (offline) implementation of a generation stage.

Moved verbatim from ``app/orchestrator/nodes/scaffolder_node.py`` as part of T020.
The f-string logic is unchanged: identical input MUST yield identical output,
identical disk writes, and identical return values. That equivalence is what
keeps the frozen pre-migration baseline a valid comparison target.

The node module of the same name now delegates to the stage execution
boundary, which dispatches here for DETERMINISTIC sessions.
"""

import os
from pathlib import Path
from typing import Dict, Any, Optional
from app.orchestrator.state import GenerationAgentState
from app.models.session import SessionPhase
from app.models.blueprint import ArchitectureBlueprint
from app.services.inference_engine import infer_architecture
from app.orchestrator.stages.deterministic import module_layout

def _to_pascal_case(text: str) -> str:
    cleaned = text.replace("-", " ").replace("_", " ")
    return "".join(word.capitalize() for word in cleaned.split())

def _architecture_plan(state: GenerationAgentState) -> Optional[Dict[str, Any]]:
    """Infer the ArchitecturePlan when the blueprint carries an inputInterface.

    Returns None when there is no interface (or it cannot be validated), so the
    emitted scaffolding is byte-identical to the pre-reframing output in that
    case. The plan is recorded in state for downstream stages and the API; it does
    not, by itself, change the emitted files (see the follow-up for DB/libraries).
    """
    blueprint = state.get("blueprint") or {}
    if not isinstance(blueprint, dict) or not blueprint.get("inputInterface"):
        return None
    try:
        validated = ArchitectureBlueprint.model_validate(blueprint)
        return infer_architecture(validated).model_dump()
    except Exception:  # noqa: BLE001 — a partial/untrusted blueprint must not break scaffolding
        return None

def emit(state: GenerationAgentState) -> Dict[str, Any]:
    blueprint = state.get("blueprint", {})
    service_name = blueprint.get("serviceName") or blueprint.get("service_name", "sample-service")
    package_name = blueprint.get("packageName") or blueprint.get("package_name", "com.corp.service")
    workspace_path = state.get("workspace_path", "./workspaces/sample")
    generated_files = state.get("generated_files", {})
    logs = state.get("logs", [])

    logs.append(f"[SCAFFOLDER] Generating project scaffolding for {service_name}")
    pascal_name = _to_pascal_case(service_name)
    pkg_path = package_name.replace(".", "/")
    plan = _architecture_plan(state)
    multi = module_layout.is_multi_module(plan)
    prefix = module_layout.module_prefix_for("SCAFFOLDER", plan)

    # 1. pom.xml with Java 21, Spring Boot 3.2.3, Mockito
    pom_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.3</version>
        <relativePath/>
    </parent>
    <groupId>{package_name}</groupId>
    <artifactId>{service_name}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>{service_name}</name>
    <description>Autonomous Microservice generated by Microservice Code Studio</description>
    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>
            </plugin>
        </plugins>
    </build>
</project>
"""

    # 2. application.yml
    app_yml = f"""spring:
  application:
    name: {service_name}
  datasource:
    url: jdbc:h2:mem:{service_name.replace('-', '_')};DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
"""

    # 3. Application.java
    app_java = f"""package {package_name};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class {pascal_name}Application {{
    public static void main(String[] args) {{
        SpringApplication.run({pascal_name}Application.class, args);
    }}
}}
"""

    # 3b. Production datasource, externalized as a Spring profile. The hermetic
    # offline build always runs against H2 (in-memory); the durable target the
    # inference chose is materialized here so credentials stay OUT of code and OUT
    # of the default config (Constitution VI / "credenciales en archivo externo").
    if plan is not None and plan["databaseType"] == "postgresql":
        prod_yml = f"""spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/{service_name}
    driverClassName: org.postgresql.Driver
    username: ${{DB_USERNAME}}
    password: ${{DB_PASSWORD}}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
"""
        generated_files[f"{prefix}src/main/resources/application-prod.yml"] = prod_yml

    selected_build = (blueprint.get("inputInterface") or {}).get("buildToolPreference") or (plan or {}).get("buildTool", "maven")
    if selected_build == "gradle":
        generated_files.update(module_layout.render_gradle_builds(service_name, package_name, multi))
    elif multi:
        # "capa X en proyecto Y": one Maven module per layer.
        generated_files.update(module_layout.render_reactor_poms(service_name, package_name, plan))
    else:
        generated_files["pom.xml"] = pom_xml
    generated_files[f"{prefix}src/main/resources/application.yml"] = app_yml
    generated_files[f"{prefix}src/main/java/{pkg_path}/{pascal_name}Application.java"] = app_java

    # Write files to disk
    base_dir = Path(workspace_path)
    for rel_path, content in generated_files.items():
        file_path = base_dir / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")

    logs.append(f"[SCAFFOLDER] Created pom.xml, application.yml, and {pascal_name}Application.java")

    result: Dict[str, Any] = {
        "current_phase": SessionPhase.CODE_GENERATION.value,
        "generated_files": generated_files,
        "logs": logs,
    }
    if plan is not None:
        result["architecture_plan"] = plan
        logs.append(f"[SCAFFOLDER] architecture inferred: {plan['profile']} / {plan['buildTool']} / {plan['databaseType']}")
    return result
