-- ============================================================================
-- Microservice Code Studio: Relational Schema DDL (fallback from blueprint)
-- Dialect: ANSI SQL / PostgreSQL & H2 (MODE=PostgreSQL) Compatible
-- ============================================================================

CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT
);
