import { describe, it, expect, vi, beforeEach } from 'vitest';
import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { VisualDataModelViewer } from '../components/models/VisualDataModelViewer';
import { VisualSqlViewer } from '../components/models/VisualSqlViewer';

const mockEntities = [
  {
    name: 'Order',
    tableName: 'orders',
    packageName: 'com.tcs.order.model',
    description: 'Order aggregate root',
    attributes: [
      { name: 'id', columnName: 'id', javaType: 'Long', sqlType: 'BIGINT', isPrimaryKey: true, nullable: false },
      { name: 'orderNumber', columnName: 'order_number', javaType: 'String', sqlType: 'VARCHAR(255)', isUnique: true, nullable: false, validationRules: ['@NotBlank'] },
      { name: 'totalAmount', columnName: 'total_amount', javaType: 'BigDecimal', sqlType: 'NUMERIC(19, 2)', nullable: false },
      { name: 'createdAt', columnName: 'created_at', javaType: 'Instant', sqlType: 'TIMESTAMP WITH TIME ZONE', nullable: false },
    ],
    relationships: [
      {
        sourceEntity: 'Order',
        targetEntity: 'OrderItem',
        relationshipType: 'ONE_TO_MANY',
        joinColumnName: 'order_id',
        inversePropertyName: 'orderItems',
        cascadeType: 'ALL',
        fetchType: 'LAZY',
      },
    ],
  },
  {
    name: 'OrderItem',
    tableName: 'order_items',
    packageName: 'com.tcs.order.model',
    attributes: [
      { name: 'id', columnName: 'id', javaType: 'Long', sqlType: 'BIGINT', isPrimaryKey: true, nullable: false },
      { name: 'productName', columnName: 'product_name', javaType: 'String', sqlType: 'VARCHAR(255)', nullable: false },
      { name: 'orderId', columnName: 'order_id', javaType: 'Long', sqlType: 'BIGINT', hasIndex: true, nullable: false },
    ],
    relationships: [
      {
        sourceEntity: 'OrderItem',
        targetEntity: 'Order',
        relationshipType: 'MANY_TO_ONE',
        joinColumnName: 'order_id',
        inversePropertyName: 'orderItems',
      },
    ],
  },
];

const mockDdl = `
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(255) NOT NULL UNIQUE,
    total_amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    order_id BIGINT NOT NULL,
    CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
`;

const mockDml = `
INSERT INTO orders (id, order_number, total_amount) VALUES (1, 'ORD-2026-001', 199.99);
INSERT INTO order_items (id, product_name, order_id) VALUES (1, 'Cloud Subscription', 1);
`;

describe('VisualDataModelViewer', () => {
  it('renders interactive relational ER diagram canvas with cardinalities by default', () => {
    render(
      <VisualDataModelViewer
        entities={mockEntities}
        serviceName="order-service"
        packageName="com.tcs.order"
      />
    );

    // Default tab is Diagrama ER Relacional
    expect(screen.getByRole('button', { name: /Diagrama ER Relacional/i })).toBeInTheDocument();
    expect(screen.getByText(/Diagrama Entidad-Relación Dinámico/i)).toBeInTheDocument();

    // Table names in ERD canvas
    expect(screen.getByText('ORDERS')).toBeInTheDocument();
    expect(screen.getByText('ORDER_ITEMS')).toBeInTheDocument();

    // Cardinality labels
    expect(screen.getByText('(1,1)')).toBeInTheDocument();
  });

  it('switches to logical domain model with Java types and business relationships', () => {
    render(
      <VisualDataModelViewer
        entities={mockEntities}
        serviceName="order-service"
        packageName="com.tcs.order"
      />
    );

    const logicalBtn = screen.getByRole('button', { name: /Modelo Lógico \(Dominio\)/i });
    fireEvent.click(logicalBtn);

    // Logical tab active
    expect(screen.getByText(/Vista de Modelo Lógico \(Entidades de Dominio & Contratos JPA\)/i)).toBeInTheDocument();

    // Entity Order and attributes
    expect(screen.getByRole('heading', { name: 'Order' })).toBeInTheDocument();
    expect(screen.getByText('orderNumber')).toBeInTheDocument();
    expect(screen.getByText('BigDecimal')).toBeInTheDocument();
    expect(screen.getByText('@NotBlank')).toBeInTheDocument();

    // Relationships
    expect(screen.getByText(/Uno a Muchos/i)).toBeInTheDocument();
  });

  it('switches to physical relational model with SQL types and tables', () => {
    render(
      <VisualDataModelViewer
        entities={mockEntities}
        serviceName="order-service"
      />
    );

    const physicalBtn = screen.getByRole('button', { name: /Modelo Físico \(Tablas SQL\)/i });
    fireEvent.click(physicalBtn);

    expect(screen.getByText(/Vista de Modelo Físico Relacional/i)).toBeInTheDocument();
    expect(screen.getByText(/TABLA: orders/i)).toBeInTheDocument();
    expect(screen.getByText(/TABLA: order_items/i)).toBeInTheDocument();
    expect(screen.getByText('order_number')).toBeInTheDocument();
    expect(screen.getByText('NUMERIC(19, 2)')).toBeInTheDocument();
  });

  it('switches to interactive ER graph and inspects relationships', () => {
    render(
      <VisualDataModelViewer
        entities={mockEntities}
        serviceName="order-service"
      />
    );

    const graphBtn = screen.getByRole('button', { name: /Grafo ER Interactivo/i });
    fireEvent.click(graphBtn);

    expect(screen.getByText(/Grafo Interactivo de Entidades y Relaciones/i)).toBeInTheDocument();
    expect(screen.getByText(/Inspector de Relaciones para Entidad/i)).toBeInTheDocument();
  });

  it('filters entities by search term', () => {
    render(
      <VisualDataModelViewer
        entities={mockEntities}
        serviceName="order-service"
      />
    );

    const searchInput = screen.getByPlaceholderText(/Buscar entidad, columna, tipo/i);
    fireEvent.change(searchInput, { target: { value: 'product' } });

    // OrderItem matches product_name, Order does not
    expect(screen.getByText('ORDER_ITEMS')).toBeInTheDocument();
    expect(screen.queryByText('ORDERS')).not.toBeInTheDocument();
  });
});

describe('VisualSqlViewer', () => {
  it('renders visual table schema inspector by default', () => {
    render(
      <VisualSqlViewer
        schemaDdl={mockDdl}
        seedDml={mockDml}
        entities={mockEntities}
        dialect="PostgreSQL 16 & H2"
      />
    );

    expect(screen.getByText(/Esquema Visual de Tablas/i)).toBeInTheDocument();
    expect(screen.getByText(/PostgreSQL 16 & H2/i)).toBeInTheDocument();
    expect(screen.getByText('orders')).toBeInTheDocument();
    expect(screen.getByText('order_items')).toBeInTheDocument();
  });

  it('switches to visual seed data grid and shows parsed records', () => {
    render(
      <VisualSqlViewer
        schemaDdl={mockDdl}
        seedDml={mockDml}
        entities={mockEntities}
      />
    );

    const dataTabBtn = screen.getByRole('button', { name: /Grid Visual de Datos Semilla/i });
    fireEvent.click(dataTabBtn);

    expect(screen.getByText(/Visualización de Datos Semilla & Fixtures de Prueba/i)).toBeInTheDocument();
    expect(screen.getByText('ORD-2026-001')).toBeInTheDocument();
    expect(screen.getByText('199.99')).toBeInTheDocument();
  });

  it('switches to schema.sql and data.sql code tabs', () => {
    render(
      <VisualSqlViewer
        schemaDdl={mockDdl}
        seedDml={mockDml}
        entities={mockEntities}
      />
    );

    const ddlTabBtn = screen.getByRole('button', { name: /schema\.sql \(DDL\)/i });
    fireEvent.click(ddlTabBtn);
    expect(screen.getByText(/Script DDL ANSI \/ PostgreSQL 16/i)).toBeInTheDocument();

    const dmlTabBtn = screen.getByRole('button', { name: /data\.sql \(DML\)/i });
    fireEvent.click(dmlTabBtn);
    expect(screen.getByText(/Script DML de Semillas & Fixtures de Datos/i)).toBeInTheDocument();
  });
});
