"""Native Quarkus offline generator, restored and wired into the Studio stage boundary."""

import os
from pathlib import Path
from typing import Dict, Any
from app.orchestrator.state import GenerationAgentState
from app.models.session import SessionPhase

def emit(state: GenerationAgentState) -> Dict[str, Any]:
    blueprint = state.get("blueprint", {})
    service_name = blueprint.get("serviceName") or blueprint.get("service_name", "sample-service")
    package_name = blueprint.get("packageName") or blueprint.get("package_name", "com.corp.service")
    workspace_path = state.get("workspace_path", "./workspaces/sample")
    generated_files = state.get("generated_files", {})
    logs = state.get("logs", [])

    logs.append(f"[SCAFFOLDER] Generating project scaffolding for {service_name}")
    port = int(blueprint.get('basePort', 8080))
    selected_database = str(blueprint.get('databaseMode', 'H2')).upper().replace(' ', '')
    databases = {
        'H2': ('h2', 'quarkus-jdbc-h2', f'jdbc:h2:mem:{service_name};DB_CLOSE_DELAY=-1'),
        'POSTGRESQL': ('postgresql', 'quarkus-jdbc-postgresql', f'jdbc:postgresql://localhost:5432/{service_name.replace("-", "_")}'),
        'MYSQL': ('mysql', 'quarkus-jdbc-mysql', f'jdbc:mysql://localhost:3306/{service_name.replace("-", "_")}'),
    }
    if selected_database not in databases:
        raise ValueError('Unsupported database for the Quarkus Studio: ' + selected_database)
    database_kind, driver, jdbc_url = databases[selected_database]
    production_dependency = '' if driver == 'quarkus-jdbc-h2' else f'<dependency><groupId>io.quarkus</groupId><artifactId>{driver}</artifactId></dependency>'

    # The Quarkus platform BOM version. Kept as a single constant so it is easy
    # to bump against whatever version the team's offline Maven mirror actually
    # carries -- there is no way to confirm "latest" from here without network
    # access, so this is a known-good pin, not a claim of currency.
    quarkus_version = "3.15.1"

    # 1. pom.xml with Java 21, Quarkus, Mockito
    pom_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>{package_name}</groupId>
    <artifactId>{service_name}</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>{service_name}</name>
    <description>Autonomous Microservice generated by Microservice Code Studio</description>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.release>21</maven.compiler.release>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.version>{quarkus_version}</quarkus.platform.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${{quarkus.platform.group-id}}</groupId>
                <artifactId>${{quarkus.platform.artifact-id}}</artifactId>
                <version>${{quarkus.platform.version}}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        {production_dependency}
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-h2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5-mockito</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>${{quarkus.platform.group-id}}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${{quarkus.platform.version}}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
"""

    # 2. application.properties (Quarkus convention; replaces application.yml)
    app_properties = f"""quarkus.application.name={service_name}
quarkus.http.port={port}
quarkus.http.cors=true

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:{service_name.replace('-', '_')};DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false
%test.quarkus.http.test-port=0
%prod.quarkus.datasource.db-kind={database_kind}
%prod.quarkus.datasource.jdbc.url=${{DB_URL:{jdbc_url}}}
%prod.quarkus.datasource.username=${{DB_USER:sa}}
%prod.quarkus.datasource.password=${{DB_PASSWORD:}}
"""

    generated_files["pom.xml"] = pom_xml
    generated_files["src/main/resources/application.properties"] = app_properties

    # No Application.java / main class is emitted: Quarkus does not need one --
    # CDI beans and JAX-RS resources are enough for the app to boot, and adding
    # a hand-written main class here would just be dead code the generator has
    # to keep in sync with nothing.

    # Write files to disk
    base_dir = Path(workspace_path)
    for rel_path, content in generated_files.items():
        file_path = base_dir / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")

    logs.append("[SCAFFOLDER] Created pom.xml and application.properties (Quarkus)")

    return {
        "current_phase": SessionPhase.CODE_GENERATION.value,
        "generated_files": generated_files,
        "logs": logs
    }
