-- ============================================================================
-- Microservice Code Studio: Relational Schema DDL (fallback from blueprint)
-- Dialect: H2
-- ============================================================================

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL
);
