"""QE coverage: the generated schema must describe the service it ships with.

Raised by an external review of real generated output, which found a service whose
``schema.sql`` created a table ``items`` while its JPA entity mapped ``orders``.
``docker-compose.yml`` mounts ``schema.sql`` into
``/docker-entrypoint-initdb.d/``, so under ``ddl-auto: validate`` the application
refuses to start against the database its own schema just created.

Tracing it found two defects stacked on top of each other:

1. ``pipeline_runner`` read ``sql_resp.schemaSql``, an attribute that does not
   exist. The response nests the scripts as ``sqlSchema.schemaDdl`` / ``seedDml``.
   The resulting ``AttributeError`` was swallowed by a broad ``except``, so **every**
   generated project silently took the fallback path.
2. That fallback wrote a hardcoded ``items`` table regardless of the blueprint.

A silent fallback is indistinguishable from a successful synthesis, which is why
neither defect was visible in 15 measured sessions. Both are fixed; these tests pin
them so a typo cannot be absorbed again.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from app.models.requirements import SpecificationDraft  # noqa: E402
from app.services.conformance_diagnostics import (  # noqa: E402
    RULE_SCHEMA_ENTITY_MISMATCH,
    check_schema_matches_entities,
    diagnose,
)
from app.services.model_sql_service import (  # noqa: E402
    model_sql_service,
    schema_sql_from_draft,
)

ENTITY_JAVA = """package com.corp.order.model.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "orders")
public class Order {
    @Id
    private Long id;
}
"""

SCHEMA_CORRECT = "CREATE TABLE IF NOT EXISTS orders (\n    id BIGINT PRIMARY KEY\n);\n"
# The exact table the old fallback emitted, whatever the blueprint said.
SCHEMA_WRONG = (
    "CREATE TABLE IF NOT EXISTS items (\n"
    "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n"
    "    name VARCHAR(255) NOT NULL,\n"
    "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n"
    ");\n"
)


def _draft():
    return SpecificationDraft.model_validate({
        "serviceName": "order-service", "packageName": "com.corp.order",
        "basePort": 8080, "assumptions": [], "userStories": [],
        "entities": [{
            "name": "Order", "tableName": "orders",
            "attributes": [
                {"name": "id", "type": "Long", "isPrimaryKey": True},
                {"name": "customerEmail", "type": "String", "nullable": False},
                {"name": "totalAmount", "type": "BigDecimal", "nullable": False},
            ],
        }],
    })


# ---------------------------------------------------------------------------
# The rule
# ---------------------------------------------------------------------------
def test_a_schema_that_omits_the_entity_table_is_reported():
    """The colleague's exact case: entity maps `orders`, schema creates `items`."""
    files = {
        "schema.sql": SCHEMA_WRONG,
        "src/main/java/com/corp/order/model/entity/Order.java": ENTITY_JAVA,
    }

    violations = check_schema_matches_entities(files)

    assert len(violations) == 1
    violation = violations[0]
    assert violation.rule_id == RULE_SCHEMA_ENTITY_MISMATCH
    assert "orders" in violation.message
    assert "items" in violation.message, "the report does not say what was created instead"
    assert violation.artifact_path == "schema.sql"
    assert violation.blocking is True, "a service that cannot start is not a warning"


def test_the_rule_is_accumulated_not_local():
    """No single stage owns both files, so a stage must not be rejected for it."""
    files = {
        "schema.sql": SCHEMA_WRONG,
        "src/main/java/com/corp/order/model/entity/Order.java": ENTITY_JAVA,
    }

    violation = check_schema_matches_entities(files)[0]

    assert violation.attribution == "ACCUMULATED"
    assert violation.contributing_sources


def test_a_consistent_schema_reports_nothing():
    files = {
        "schema.sql": SCHEMA_CORRECT,
        "src/main/java/com/corp/order/model/entity/Order.java": ENTITY_JAVA,
    }

    assert check_schema_matches_entities(files) == []


@pytest.mark.parametrize(
    "name_style",
    ['@Table(name = "orders")', "@Table(name='orders')", '@Table( name = "orders" )'],
)
def test_the_annotation_is_matched_regardless_of_quoting_or_spacing(name_style):
    files = {
        "schema.sql": SCHEMA_WRONG,
        "src/main/java/com/corp/order/model/entity/Order.java": name_style,
    }

    assert len(check_schema_matches_entities(files)) == 1


def test_an_entity_without_an_explicit_table_name_is_not_flagged():
    """Default JPA naming is a different question; this rule compares declarations."""
    files = {
        "schema.sql": SCHEMA_WRONG,
        "src/main/java/com/corp/order/model/entity/Order.java": "@Entity\npublic class Order {}",
    }

    assert check_schema_matches_entities(files) == []


def test_no_schema_file_means_nothing_to_compare():
    """Absence is not a finding: an entity-only workspace is not evaluable here."""
    assert check_schema_matches_entities({"Order.java": ENTITY_JAVA}) == []


def test_a_schema_with_no_create_statements_is_not_flagged():
    files = {"schema.sql": "-- nothing here\n", "Order.java": ENTITY_JAVA}

    assert check_schema_matches_entities(files) == []


def test_the_rule_reaches_the_diagnostic_report():
    """End to end through diagnose(): the finding lands in the histogram."""
    files = {
        "schema.sql": SCHEMA_WRONG,
        "src/main/java/com/corp/order/model/entity/Order.java": ENTITY_JAVA,
    }

    report = diagnose(files)

    assert RULE_SCHEMA_ENTITY_MISMATCH in report.rule_histogram
    assert RULE_SCHEMA_ENTITY_MISMATCH in report.rule_ids
    assert report.blocking is True


# ---------------------------------------------------------------------------
# The fallback must describe THIS service
# ---------------------------------------------------------------------------
def test_the_fallback_derives_the_table_from_the_blueprint():
    sql = schema_sql_from_draft(_draft())

    assert "CREATE TABLE IF NOT EXISTS orders" in sql
    assert "customer_email VARCHAR(255) NOT NULL" in sql
    assert "total_amount NUMERIC(19, 2) NOT NULL" in sql
    assert "items" not in sql, "the fallback still emits the hardcoded table"


def test_the_fallback_covers_every_entity():
    draft = SpecificationDraft.model_validate({
        "serviceName": "shop", "packageName": "com.corp.shop", "basePort": 8080,
        "assumptions": [], "userStories": [],
        "entities": [
            {"name": "Order", "tableName": "orders", "attributes": [
                {"name": "id", "type": "Long", "isPrimaryKey": True}]},
            {"name": "Item", "tableName": "items", "attributes": [
                {"name": "id", "type": "Long", "isPrimaryKey": True}]},
        ],
    })

    sql = schema_sql_from_draft(draft)

    assert "CREATE TABLE IF NOT EXISTS orders" in sql
    assert "CREATE TABLE IF NOT EXISTS items" in sql


def test_an_entity_with_no_attributes_cannot_be_constructed():
    """The contract forbids it, so the defensive branch below is unreachable today.

    Asserted rather than deleted: if the minimum is ever relaxed, the fallback's
    no-columns guard becomes live and this test is where the change shows up.
    """
    from pydantic import ValidationError

    with pytest.raises(ValidationError):
        SpecificationDraft.model_validate({
            "serviceName": "shop", "packageName": "com.corp.shop", "basePort": 8080,
            "assumptions": [], "userStories": [],
            "entities": [{"name": "Empty", "tableName": "empties", "attributes": []}],
        })


def test_a_blueprint_with_no_entities_says_so():
    draft = SpecificationDraft.model_validate({
        "serviceName": "shop", "packageName": "com.corp.shop", "basePort": 8080,
        "assumptions": [], "userStories": [], "entities": [],
    })

    assert "declared no entities" in schema_sql_from_draft(draft)


# ---------------------------------------------------------------------------
# The typo regression: pin the attribute path the pipeline reads
# ---------------------------------------------------------------------------
def test_the_synthesis_response_exposes_the_attributes_the_pipeline_reads():
    """`sqlSchema.schemaDdl`, not `schemaSql`.

    This is the defect that made every project take the fallback: the attribute did
    not exist, a broad `except` swallowed the AttributeError, and silence looked like
    success. Asserting the shape is what stops a rename from reintroducing it.
    """
    response = model_sql_service.synthesize_domain_models_and_sql(
        _draft(), api_key="mock-key", provider="mock",
    )

    assert hasattr(response, "sqlSchema"), "the pipeline reads response.sqlSchema"
    assert hasattr(response.sqlSchema, "schemaDdl")
    assert hasattr(response.sqlSchema, "seedDml")
    assert "CREATE TABLE IF NOT EXISTS orders" in response.sqlSchema.schemaDdl
    assert not hasattr(response, "schemaSql"), (
        "the attribute the pipeline used to read does not exist; if it appears, the "
        "field was renamed and pipeline_runner must be updated in the same change"
    )
