import pytest
from integration.reliability_fixtures import ledger_draft


def test_complete_descriptor_preserves_custom_identifier_dates_and_rules():
    from app.services.domain_descriptor import normalize_blueprint, identifier, java_type, constraints
    draft=normalize_blueprint(ledger_draft())
    assert identifier(draft['entities'][0]) == ('entryId','java.util.UUID')
    assert java_type('java.time.Instant') == 'java.time.Instant'
    assert java_type('LocalDate') == 'java.time.LocalDate'
    assert java_type('LocalDateTime') == 'java.time.LocalDateTime'
    assert constraints(draft['entities'][0]['attributes'][1]) == ['@NotBlank','@Email']
    assert draft['entities'][0]['attributes'][1]['isUnique']

@pytest.mark.parametrize('mutation', ['package','entity','field','table','constraint','unknown-type','composite'])
def test_invalid_descriptors_fail_before_writing(mutation,tmp_path):
    from app.services.domain_descriptor import normalize_blueprint
    draft=ledger_draft();entity=draft['entities'][0];attribute=entity['attributes'][1]
    if mutation=='package': draft['packageName']='com.bad/../../outside'
    elif mutation=='entity': entity['name']='../Outside'
    elif mutation=='field': attribute['name']='class'
    elif mutation=='table': entity['tableName']='entries;DROP TABLE users'
    elif mutation=='constraint': attribute['validationRules']=['@Size(min=)']
    elif mutation=='unknown-type': attribute['type']='File; static { dangerous(); }'
    else: attribute['isPrimaryKey']=True
    with pytest.raises(ValueError): normalize_blueprint(draft)
    assert not list(tmp_path.iterdir())


def test_typed_draft_preserves_column_names_and_explicit_uniqueness():
    from app.models.requirements import SpecificationDraft
    from app.services.model_sql_service import schema_sql_from_draft
    draft=ledger_draft();attribute=draft['entities'][0]['attributes'][1]
    attribute['columnName']='contact_email';attribute['isUnique']=False
    typed=SpecificationDraft.model_validate(draft)
    assert typed.entities[0].attributes[1].columnName=='contact_email'
    sql=schema_sql_from_draft(typed,'MYSQL')
    assert 'contact_email VARCHAR' in sql
    assert ' UNIQUE' not in sql


def test_implicit_identifier_agrees_between_migration_and_java():
    from app.models.requirements import SpecificationDraft
    from app.services.model_sql_service import schema_sql_from_draft
    draft=ledger_draft();draft['entities'][0]['attributes'].pop(0)
    sql=schema_sql_from_draft(SpecificationDraft.model_validate(draft),'H2')
    assert 'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' in sql
