"""Platform-authored verification: an acceptance signal the generator cannot author.

The point of these tests is not that the generated Java is pretty. It is that the
platform owns a check the model cannot see, edit, or learn from, and that its
**absence is reported rather than mistaken for a pass** -- the failure mode
feature 012 already established one level up.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from app.services.platform_verification import (  # noqa: E402
    base_package,
    inject_contract_test,
    render_contract_test,
    repository_types,
    strip_vcs_metadata,
)

APP_SOURCE = """package com.acme.orders;

import org.springframework.boot.SpringApplication;

public class OrdersApplication {
    public static void main(String[] args) {
        SpringApplication.run(OrdersApplication.class, args);
    }
}
"""

REPO_SOURCE = """package com.acme.orders.repository;

import org.springframework.data.jpa.repository.JpaRepository;

public interface OrderRepository extends JpaRepository<Order, Long> {
}
"""

REPO_SOURCE_TWO = """package com.acme.orders.repository;

import org.springframework.data.jpa.repository.JpaRepository;

public interface CustomerRepository extends JpaRepository<Customer, Long> {
}
"""

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
"""


def _workspace(tmp_path: Path, *, app=True, schema=True, repos=True, name="ws") -> Path:
    ws = tmp_path / name
    main = ws / "src" / "main" / "java" / "com" / "acme" / "orders"
    main.mkdir(parents=True, exist_ok=True)
    if app:
        (main / "OrdersApplication.java").write_text(APP_SOURCE, encoding="utf-8")
    if repos:
        repo_dir = main / "repository"
        repo_dir.mkdir(parents=True, exist_ok=True)
        (repo_dir / "OrderRepository.java").write_text(REPO_SOURCE, encoding="utf-8")
        (repo_dir / "CustomerRepository.java").write_text(REPO_SOURCE_TWO, encoding="utf-8")
    if schema:
        (ws / "schema.sql").write_text(SCHEMA_SQL, encoding="utf-8")
    return ws


def test_the_base_package_is_read_from_the_generated_entry_point(tmp_path):
    """The blueprint carries no package name, so it must be derived, not assumed."""
    assert base_package(_workspace(tmp_path)) == "com.acme.orders"


def test_repository_types_are_discovered_with_their_package(tmp_path):
    assert repository_types(_workspace(tmp_path)) == [
        ("CustomerRepository", "com.acme.orders.repository"),
        ("OrderRepository", "com.acme.orders.repository"),
    ]


def test_the_contract_test_validates_rather_than_generates_the_schema(tmp_path):
    """`ddl-auto=create` would make the test pass by construction and prove nothing.

    The whole value is that Hibernate is asked to *check* the entity mappings
    against the project's own schema.sql, so a contradiction fails the build.
    """
    rendered = render_contract_test(_workspace(tmp_path))
    assert rendered is not None
    rel_path, content = rendered

    assert rel_path == "src/test/java/com/acme/orders/PlatformPersistenceContractTest.java"
    assert "ddl-auto=validate" in content
    assert "ddl-auto=create" not in content
    assert "schema-locations=file:./schema.sql" in content
    # Both repositories must be resolved as beans, which is what exercises wiring.
    assert content.count("context.getBean(") == 2
    assert "import com.acme.orders.repository.OrderRepository;" in content


def test_the_test_never_uses_a_generated_or_placeholder_assertion(tmp_path):
    rendered = render_contract_test(_workspace(tmp_path))
    assert rendered is not None
    _, content = rendered
    # A test that cannot fail is not a check; `assertThat(context).isNotNull()`
    # is a real assertion about a real object, but `assertTrue(true)` is not.
    assert "assertTrue(true)" not in content
    assert "assertThat(context).isNotNull();" in content


def test_absence_of_preconditions_is_reported_as_none(tmp_path):
    """None is 'no platform verification ran', which the caller must surface."""
    assert render_contract_test(_workspace(tmp_path, schema=False, name="no-schema")) is None
    assert render_contract_test(_workspace(tmp_path, app=False, name="no-app")) is None
    assert render_contract_test(_workspace(tmp_path, repos=False, name="no-repos")) is None


def test_injection_writes_the_file_into_the_workspace(tmp_path):
    ws = _workspace(tmp_path)
    written = inject_contract_test(str(ws))

    assert written is not None
    target = ws / written
    assert target.is_file()
    assert "PlatformPersistenceContractTest" in target.read_text(encoding="utf-8")


def test_injection_is_a_no_op_when_it_cannot_verify(tmp_path):
    ws = _workspace(tmp_path, schema=False)
    assert inject_contract_test(str(ws)) is None
    assert not list((ws / "src" / "test").rglob("*.java")) if (ws / "src" / "test").exists() else True


def test_vcs_metadata_is_stripped(tmp_path):
    """A .git in a scaffolded workspace hands the build whatever history it holds."""
    ws = _workspace(tmp_path)
    git_dir = ws / ".git"
    git_dir.mkdir()
    (git_dir / "config").write_text("[core]\n", encoding="utf-8")

    removed = strip_vcs_metadata(str(ws))

    assert ".git" in removed
    assert not git_dir.exists()


def test_stripping_reports_nothing_when_there_is_nothing_to_strip(tmp_path):
    assert strip_vcs_metadata(str(_workspace(tmp_path))) == ()
