import pytest
from fastapi.testclient import TestClient

from app.main import app
from app.models.requirements import SpecificationDraft
from app.models.blueprint import DomainEntity, EntityAttribute, UserStoryRecord, AcceptanceScenarioRecord

client = TestClient(app)

@pytest.fixture
def sample_specification_draft() -> SpecificationDraft:
    return SpecificationDraft(
        serviceName="order-service",
        packageName="com.example.orderservice",
        basePort=8080,
        entities=[
            DomainEntity(
                name="Order",
                tableName="orders",
                attributes=[
                    EntityAttribute(name="id", type="Long", isPrimaryKey=True),
                    EntityAttribute(name="orderNumber", type="String", isPrimaryKey=False),
                    EntityAttribute(name="totalAmount", type="BigDecimal", isPrimaryKey=False),
                    EntityAttribute(name="status", type="String", isPrimaryKey=False),
                ]
            ),
            DomainEntity(
                name="OrderItem",
                tableName="order_items",
                attributes=[
                    EntityAttribute(name="id", type="Long", isPrimaryKey=True),
                    EntityAttribute(name="productName", type="String", isPrimaryKey=False),
                    EntityAttribute(name="unitPrice", type="BigDecimal", isPrimaryKey=False),
                    EntityAttribute(name="quantity", type="Integer", isPrimaryKey=False),
                ]
            )
        ],
        userStories=[
            UserStoryRecord(
                id="US-1",
                role="Customer",
                intent="place an order",
                benefit="receive items",
                scenarios=[
                    AcceptanceScenarioRecord(
                        scenarioId="AC-1.1",
                        given="a customer with items in cart",
                        when="submitting checkout",
                        then="create order and return status 201"
                    ),
                    AcceptanceScenarioRecord(
                        scenarioId="AC-1.2",
                        given="an order with empty cart",
                        when="submitting checkout",
                        then="return 400 Bad Request"
                    )
                ]
            )
        ]
    )

def test_generate_models_missing_api_key_401(sample_specification_draft: SpecificationDraft, monkeypatch):
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)
    monkeypatch.delenv("GOOGLE_API_KEY", raising=False)
    monkeypatch.delenv("GROQ_API_KEY", raising=False)
    payload = {
        "draft": sample_specification_draft.model_dump(),
        "apiKey": None
    }
    resp = client.post("/api/v1/models/generate", json=payload)
    assert resp.status_code == 401
    data = resp.json()
    error_msg = data.get("detail") or data.get("message", "")
    assert "API key" in error_msg

def test_generate_models_endpoint_success(sample_specification_draft: SpecificationDraft):
    payload = {
        "draft": sample_specification_draft.model_dump(),
        "apiKey": "mock-test-key"
    }
    resp = client.post("/api/v1/models/generate", json=payload)
    assert resp.status_code == 200
    data = resp.json()

    assert data["serviceName"] == "order-service"
    assert data["packageName"] == "com.example.orderservice"
    assert len(data["entities"]) >= 2
    assert "schema.sql" not in data["sqlSchema"]  # schemaDdl is a field
    assert "CREATE TABLE IF NOT EXISTS orders" in data["sqlSchema"]["schemaDdl"]
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in data["sqlSchema"]["schemaDdl"]
    assert "created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP" in data["sqlSchema"]["schemaDdl"]
    assert "INSERT INTO orders" in data["sqlSchema"]["seedDml"]
    assert "erDiagram" in data["mermaidErDiagram"]
    assert "Order" in data["javaEntityClasses"]
    assert "@Entity" in data["javaEntityClasses"]["Order"]

def test_refine_models_endpoint_success(sample_specification_draft: SpecificationDraft):
    # First generate initial design
    init_payload = {
        "draft": sample_specification_draft.model_dump(),
        "apiKey": "mock-test-key"
    }
    init_resp = client.post("/api/v1/models/generate", json=init_payload)
    assert init_resp.status_code == 200
    init_data = init_resp.json()

    # Refine
    refine_payload = {
        "currentResponse": init_data,
        "feedbackPrompt": "Añade un campo trackingNumber de tipo String en Order",
        "targetEntity": "Order",
        "apiKey": "mock-test-key"
    }
    refine_resp = client.post("/api/v1/models/refine", json=refine_payload)
    assert refine_resp.status_code == 200
    refined_data = refine_resp.json()

    order_entity = next(e for e in refined_data["entities"] if e["name"] == "Order")
    attr_names = [a["name"] for a in order_entity["attributes"]]
    assert "trackingNumber" in attr_names
    assert "tracking_number" in refined_data["sqlSchema"]["schemaDdl"]
    assert "tracking_number" in refined_data["mermaidErDiagram"]

def test_handoff_to_specifications_store(sample_specification_draft: SpecificationDraft):
    payload = {
        "draft": sample_specification_draft.model_dump(),
        "apiKey": "mock-test-key"
    }
    resp = client.post("/api/v1/models/generate", json=payload)
    assert resp.status_code == 200
    model_data = resp.json()

    blueprint_payload = {
        "serviceName": model_data["serviceName"],
        "packageName": model_data["packageName"],
        "basePort": 8080,
        "entities": [
            {
                "name": e["name"],
                "tableName": e.get("tableName", e["name"].lower() + "s"),
                "attributes": [{"name": a["name"], "type": a["javaType"], "isPrimaryKey": a["isPrimaryKey"]} for a in e["attributes"]]
            }
            for e in model_data["entities"]
        ],
        "userStories": [s.model_dump() for s in sample_specification_draft.userStories]
    }

    spec_resp = client.post("/api/v1/specifications", json=blueprint_payload)
    assert spec_resp.status_code == 201
    spec_data = spec_resp.json()
    assert spec_data["serviceName"] == "order-service"
    assert "specId" in spec_data
