"""Cross-artifact consistency rules (feature 015, widened under P6).

The conformance channel only ever carried variance on *accumulated* findings --
whole-project rules that no single stage owns -- because the gate blocks local
violations before persistence. That channel held one rule and now holds three, all
of them CROSS-ARTIFACT CONSISTENCY rather than style.

**Why only consistency rules were added.** Trautsch, Herbold & Grabowski (EMSE
2023) ran PMD over every file at every commit of 23 Apache Java projects -- 146,783
file changes, 1,723 manually validated bug-inducing changes -- and found that
bug-inducing files carry *less* warning density than the rest, with a negative
median delta in 16 of 23 projects and negligible effect sizes throughout. Static
*style* rules are near-orthogonal to defects. A rule that compares two generated
artifacts against each other is a different instrument: it can only fire when the
service contradicts itself, and the schema/entity rule already found a real defect
that way.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from app.services.conformance_diagnostics import (  # noqa: E402
    RULE_SCHEMA_COLUMN_MISMATCH,
    RULE_SCHEMA_ENTITY_MISMATCH,
    check_schema_columns_match_entities,
    diagnose,
)

SCHEMA = """\
CREATE TABLE IF NOT EXISTS notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body VARCHAR(255) NOT NULL
);
"""

ENTITY = """\
package com.corp.notes.model.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "notes")
public class Note {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "body")
    private String body;
}
"""


def _files(schema: str = SCHEMA, entity: str = ENTITY):
    return {"schema.sql": schema, "src/main/java/com/corp/notes/model/entity/Note.java": entity}


def test_a_consistent_schema_and_entity_produce_no_finding():
    assert check_schema_columns_match_entities(_files()) == []


def test_an_explicitly_mapped_column_missing_from_the_table_is_reported():
    """The table exists and is named right -- the table-name rule sees nothing."""
    schema = """\
CREATE TABLE IF NOT EXISTS notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
"""
    findings = check_schema_columns_match_entities(_files(schema=schema))

    assert [f.rule_id for f in findings] == [RULE_SCHEMA_COLUMN_MISMATCH]
    assert "body" in findings[0].message


def test_an_entity_with_an_id_and_a_table_without_a_primary_key_is_reported():
    schema = """\
CREATE TABLE IF NOT EXISTS notes (
    id BIGINT,
    body VARCHAR(255)
);
"""
    findings = check_schema_columns_match_entities(_files(schema=schema))

    assert [f.rule_id for f in findings] == [RULE_SCHEMA_COLUMN_MISMATCH]
    assert "PRIMARY KEY" in findings[0].message


def test_a_bare_field_is_not_checked_because_the_naming_strategy_decides_it():
    """Deliberately narrow: guessing a column name would produce wrong findings.

    A rule that cries wolf is worse than no rule, because it teaches the operator
    to ignore the channel that survives into the saved artifact set.
    """
    entity = ENTITY.replace('    @Column(name = "body")\n', "")
    assert check_schema_columns_match_entities(_files(entity=entity)) == []


def test_an_unmapped_entity_is_left_to_the_table_name_rule():
    """No @Table: the default naming applies, and the table-name rule owns that."""
    entity = ENTITY.replace('@Table(name = "notes")\n', "")
    assert check_schema_columns_match_entities(_files(entity=entity)) == []


def test_the_finding_is_accumulated_so_it_survives_into_a_saved_artifact_set():
    """The only channel a conformance measure can vary on."""
    schema = """\
CREATE TABLE IF NOT EXISTS notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
"""
    findings = check_schema_columns_match_entities(_files(schema=schema))

    assert findings
    assert all(f.attribution == "ACCUMULATED" for f in findings)


def test_diagnose_reports_both_mismatch_kinds_through_one_entry_point():
    """End to end: the table-name rule and the new column rule are both charged."""
    schema = """\
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
"""
    report = diagnose(_files(schema=schema))

    rule_ids = {v.rule_id for v in report.violations}
    assert RULE_SCHEMA_ENTITY_MISMATCH in rule_ids, "the table-name rule must still fire"
    # The column rule stays silent here on purpose: the table does not exist, so
    # only the more specific table-name finding should be charged, not both.
    assert RULE_SCHEMA_COLUMN_MISMATCH not in rule_ids
    assert report.new_penalty > 0
